### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by Elite** [pi0/cf-kv-exporter#5]
How is this suppossed to get past the limits?

It says:

```
ℹ It is likely that you have hit the Cloudflare rate limit. Please try again later in few minutes. 
ℹ Don't worry, your progress is saved and will be resumed!  
```

**Comment by pi0** [comment]
Hi. The export progress is cached and then after ratelimit timeout it continues.

**Comment by Elite** [comment]
Yes, I get that but why not automate the script to take care of that as well?

**Comment by Elite** [comment]
Hmmm.. on second thought I guess I am using this wrong. Let me try this again.

**Comment by Elite** [comment]
How to run this with auto-continue? I am a node/npm nooobie!!

**Comment by pi0** [comment]
Simply run the script again it should continue. If not please share little more context like node version or output log so i might be able to help.

**Comment by Elite** [comment]
I have 60000+ records, this script is fetching ~ 1100 records in one go and then I have to wait and then run this again. My question is why not to automate the script to make it wait and retry after the rate-limit timeout on automated mode until all records and fetched !!

**Comment by pi0** [comment]
PR welcome to do so. I was simply lazy and needed a very quick solution that made it.

**Comment by pi0** [comment]
Moved to https://github.com/pi0/cf-kv-exporter/issues/7

If you are encountering any other issues please feel free to make a new issue.
